In [1]:
import pandas as pd
import requests
import os

Run this next season

In [2]:
#url for all calls
base_url = "https://fantasy.premierleague.com/api/"
#folder where data will be saved
season = 2627
folder = rf"C:\Users\JesseOnu\fpl sql rework\players\{season}playerid" 
output = f"{folder}.csv"

In [3]:
#call api
response = requests.get(base_url + "bootstrap-static/")

In [4]:
#convert to json
data = response.json()

In [5]:
print(type(data))
print(type(response))
print(response.status_code)

<class 'dict'>
<class 'requests.models.Response'>
200

In [6]:
#displaying availabl fields
print(data["elements"][0].keys())

dict_keys(['can_transact', 'can_select', 'chance_of_playing_next_round', 'chance_of_playing_this_round', 'code', 'cost_change_event', 'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall', 'price_change_percent', 'price_change_hourly_rate', 'price_change_projections', 'price_change_locked_until', 'price_change_calibrating', 'dreamteam_count', 'element_type', 'ep_next', 'ep_this', 'event_points', 'first_name', 'form', 'id', 'in_dreamteam', 'news', 'news_added', 'now_cost', 'photo', 'points_per_game', 'removed', 'second_name', 'selected_by_percent', 'special', 'squad_number', 'status', 'team', 'team_code', 'total_points', 'transfers_in', 'transfers_in_event', 'transfers_out', 'transfers_out_event', 'value_form', 'value_season', 'web_name', 'known_name', 'region', 'team_join_date', 'birth_date', 'has_temporary_code', 'opta_code', 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries', 'tackles', 'defensive_contribution', 'starts', 'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded', 'corners_and_indirect_freekicks_order', 'corners_and_indirect_freekicks_text', 'direct_freekicks_order', 'direct_freekicks_text', 'penalties_order', 'penalties_text', 'scout_risks', 'scout_news_link', 'influence_rank', 'influence_rank_type', 'creativity_rank', 'creativity_rank_type', 'threat_rank', 'threat_rank_type', 'ict_index_rank', 'ict_index_rank_type', 'expected_goals_per_90', 'saves_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90', 'goals_conceded_per_90', 'now_cost_rank', 'now_cost_rank_type', 'form_rank', 'form_rank_type', 'points_per_game_rank', 'points_per_game_rank_type', 'selected_rank', 'selected_rank_type', 'starts_per_90', 'clean_sheets_per_90', 'defensive_contribution_per_90'])

In [7]:
#keeping necesarry fields
df = pd.DataFrame(data["elements"])

df = df[["id", "code", "first_name", "second_name", "web_name", "photo", "element_type"]]
df['season'] = season

In [8]:
df.head()

,id,code,first_name,second_name,web_name,photo,element_type,season
0,1,154561,David,Raya Martín,Raya,154561.jpg,1,2627
1,2,109745,Kepa,Arrizabalaga Revuelta,Arrizabalaga,109745.jpg,1,2627
2,3,437495,Illan,Meslier,Meslier,437495.jpg,1,2627
3,4,226597,Gabriel,dos Santos Magalhães,Gabriel,226597.jpg,2,2627
4,5,445122,Jurriën,Timber,J.Timber,445122.jpg,2,2627

In [9]:
#replace 'jpg' with 'png' as images dont work with jpg
df['photo'] = df['photo'].str.replace('jpg', 'png', regex = False)

In [10]:
#add prefix to photo
seasonshort = 25
df['photo'] = f"https://resources.premierleague.com/premierleague{seasonshort}/photos/players/110x140/" + df['photo']
df.head(1)

,id,code,first_name,second_name,web_name,photo,element_type,season
0,1,154561,David,Raya Martín,Raya,https://resources.premierleague.com/premierlea...,1,2627

In [11]:
seasonshort

25

In [12]:
df.iloc[0]['photo']

'https://resources.premierleague.com/premierleague25/photos/players/110x140/154561.png'

In [13]:
#making sure theres no blank webnames
(df['web_name']=='').sum()

np.int64(0)

In [14]:
#check for no duplicates
df['id'].duplicated().sum()

np.int64(0)

In [15]:
df.to_csv(output, index = False)

## Changing 2526 to old photos

In [18]:
season1 = 2526
folder1 = rf"C:\Users\JesseOnu\fpl sql rework\players\{season1}playerid" 
output2 = f"{folder1}.csv"
df2 = pd.read_csv(r"C:\Users\JesseOnu\fpl sql rework\players\2526playerid.csv")

In [19]:
df2['photo'][0]

'https://resources.premierleague.com/premierleague25/photos/players/110x140/154561.png'

In [22]:
df2['photos'] = f"https://resources.premierleague.com/premierleague/photos/players/110x140/p" + df2['code'].astype(str) + ".png"
df2['photos'][0]

'https://resources.premierleague.com/premierleague/photos/players/110x140/p154561.png'

In [23]:
df2 = df2.drop(columns=['photo'])

In [26]:
df2 =df2.rename(columns ={'photos':'photo'})
df2

,id,code,first_name,second_name,web_name,element_type,season,photo
0,1,154561,David,Raya Martín,Raya,1,2526,https://resources.premierleague.com/premierlea...
1,2,109745,Kepa,Arrizabalaga Revuelta,Arrizabalaga,1,2526,https://resources.premierleague.com/premierlea...
2,3,463748,Karl,Hein,Hein,1,2526,https://resources.premierleague.com/premierlea...
3,4,551221,Tommy,Setford,Setford,1,2526,https://resources.premierleague.com/premierlea...
4,5,226597,Gabriel,dos Santos Magalhães,Gabriel,2,2526,https://resources.premierleague.com/premierlea...
...,...,...,...,...,...,...,...,...
836,809,685628,Jerome,Abbey,Abbey,3,2526,https://resources.premierleague.com/premierlea...
837,816,209041,Angel,Gomes,Angel,3,2526,https://resources.premierleague.com/premierlea...
838,817,155511,Adam,Armstrong,Armstrong,4,2526,https://resources.premierleague.com/premierlea...
839,828,491460,Alfie,Brooks,Brooks,1,2526,https://resources.premierleague.com/premierlea...
840,831,627888,Josh,Gracey,Gracey,1,2526,https://resources.premierleague.com/premierlea...

In [27]:
df2.to_csv(output2, index = False)